"""
src/agents/writer_agent.py
===========================
Writer Agent — produces the professional executive briefing.

Responsibilities:
- Synthesise research + analysis into executive-quality narrative
- McKinsey/BCG/Gartner consulting report format
- Every claim must end with [n] citation
- Generate all 12 required report sections
- Professional, board-ready language
"""

from __future__ import annotations

from typing import List, Optional

from crewai import Agent, Task
from crewai.tools import BaseTool

from config.settings import settings
from src.tools.citation_tool import citation_tool
from src.tools.report_export import report_export_tool
from src.utils.logger import get_logger

log = get_logger(__name__)


REPORT_TEMPLATE = """
# {title}

**Industry:** {industry} | **Period:** {time_period} | **Region:** {region} | **Generated:** {date}

---

## Executive Summary

[250-300 word board-ready summary of the most important competitive developments.
Lead with the most significant finding. Every sentence must have a [n] citation.]

---

## Competitor Pricing Analysis

[Pricing comparison table + 2-3 paragraph narrative with citations]

---

## Product & Feature Updates

[For each competitor: what's new, what launched, what was discontinued. Citations required.]

---

## Market Signals

[5-8 data-backed observations about the competitive landscape. Each needs a citation.]

---

## Industry Trends

[5-10 named trends with evidence. Format: **Trend Name**: Description [citation]]

---

## SWOT Analysis

| | Strengths | Weaknesses |
|---|-----------|------------|
| **Internal** | ... | ... |

| | Opportunities | Threats |
|---|--------------|---------|
| **External** | ... | ... |

---

## Risk Analysis

| Risk | Severity | Probability | Mitigation | Source |
|------|---------|------------|-----------|--------|
| ... | HIGH | ... | ... | [n] |

---

## Opportunities

| Opportunity | Impact | Timeline | Evidence |
|------------|--------|---------|---------|
| ... | HIGH | Q1 2025 | [n] |

---

## Strategic Recommendations

1. **[Action]**: [Rationale] [citation]
2. **[Action]**: [Rationale] [citation]
3. **[Action]**: [Rationale] [citation]

---

## References

[Generated by citation_manager tool]

---

## Run Metadata

[Generated automatically]

---

## Evaluation Summary

[Generated automatically]
"""


class WriterAgent:
    """CrewAI Writer Agent factory."""

    def __init__(
        self,
        model=None,          # str model name OR a crewai.llm.LLM instance
        verbose: bool = True,
        max_iter: int = 8,
        additional_tools: Optional[List[BaseTool]] = None,
    ) -> None:
        self.model = model if model is not None else settings.model_primary
        self.verbose = verbose
        self.max_iter = max_iter
        self.additional_tools = additional_tools or []
        self._agent: Optional[Agent] = None

    def build(self) -> Agent:
        """Create and return the CrewAI Agent."""
        tools = [
            citation_tool,
            report_export_tool,
            *self.additional_tools,
        ]

        self._agent = Agent(
            role="Executive Intelligence Briefing Writer",
            goal=(
                "Write a complete, professional competitive intelligence briefing in the style of "
                "McKinsey/BCG/Gartner. Every factual claim must end with [n] referencing a source. "
                "The report must include all 12 required sections. "
                "Language must be board-ready: clear, concise, evidence-based, and actionable."
            ),
            backstory=(
                "You are a former BCG and Gartner research director with 15 years of experience "
                "writing board-level intelligence reports. You have a gift for synthesising "
                "complex competitive landscapes into clear executive narratives. "
                "You never include an unsourced claim in your writing."
            ),
            tools=tools,
            verbose=self.verbose,
            allow_delegation=False,
            max_iter=self.max_iter,
            memory=True,
            llm=self.model,
        )
        return self._agent

    def create_writing_task(
        self,
        analysis_output: str,
        industry: str,
        competitors: List[str],
        region: str,
        time_period: str,
        run_id: str,
    ) -> Task:
        """Create the writing task."""
        import time as time_mod
        competitors_str = ", ".join(competitors)
        date_str = time_mod.strftime("%B %d, %Y")

        description = f"""
Write the complete Competitive Intelligence Briefing based on the analysis below.

BRIEFING PARAMETERS:
- Title: Competitive Intelligence Briefing: {industry}
- Industry: {industry}
- Competitors: {competitors_str}
- Region: {region}
- Period: {time_period}
- Date: {date_str}
- Run ID: {run_id}

MANDATORY SECTIONS (all 12 must be present):
1. Executive Summary (250-300 words, board-ready, every sentence cited)
2. Competitor Pricing Analysis (table + narrative)
3. Product & Feature Updates (by competitor)
4. Market Signals (5-8 data points)
5. Industry Trends (5-10 named trends)
6. SWOT Analysis (formatted grid)
7. Risk Analysis (ranked table)
8. Opportunities (ranked table)
9. Strategic Recommendations (3-5 actionable items)
10. References (use citation_manager action='generate_references')
11. Run Metadata (sources used, steps, cost, duration)
12. Evaluation Summary (placeholder: "Evaluation pending")

CITATION RULES:
- EVERY factual claim ends with [n]
- NO uncited assertions anywhere in the document
- Use citation_manager action='verify_citations' to check your work
- Run citation_manager action='check_claims' on the final text

WRITING STANDARDS:
- Active voice, present tense for current state
- Avoid jargon — write for a C-suite audience
- Be specific with numbers and dates from sources
- Use Markdown formatting: tables, bold for key terms, headers

ANALYSIS INPUT:
{analysis_output[:8000]}
"""

        return Task(
            description=description,
            expected_output=(
                "A complete, professional Markdown briefing document with all 12 required sections. "
                "Every factual claim has a [n] citation. References section lists all sources. "
                "Language meets McKinsey/BCG consulting quality standards. "
                "Document is immediately ready for C-suite presentation."
            ),
            agent=self._agent,
        )


def create_writer_agent(
    model: Optional[str] = None,
    verbose: bool = True,
) -> Agent:
    """Convenience factory function."""
    factory = WriterAgent(model=model, verbose=verbose)
    return factory.build()


__all__ = ["WriterAgent", "create_writer_agent"]
